---
title: "final"
author: "Anna Davtyan"
date: "2024-07-24"
output: html_document
---

```{r}
#| echo: false
#| message: false
library(tidyverse)
data <- read_csv("data/vazgen.csv")
main_data <- data |>
  filter(entry_id >= 1331 & entry_id <= 10021)
```

```{r}
#| echo: false
library(dplyr)
order <- c("N", "NE", "E", "SE", "S", "SW", "W", "NW")
main_data |>
  drop_na(direction, speed) |>
  mutate(direction = factor(direction, levels = order)) |>
  ggplot(aes(x = as.factor(direction), fill = direction)) + 
  geom_bar(width = 1) +
  coord_polar(start = -0.4) +
  labs(title = "Wind Rose", x = "Wind Direction", y = "Frequency", fill = "Direction") +
  theme_minimal()

```

```{r}
library(ggplot2)
library(lubridate)
theme_set(theme_bw())
ggplot(main_data, aes(x = time)) + 
  geom_line(aes(y = temperature, col = "temperature")) +
  labs(title = "Time Series of Returns Percentage", 
       subtitle = "Drawn From Wide Data format", 
       caption = "Source: Economics", y = "Returns %")
```

```{r}
library(ggplot2)
library(quantmod)
main_data$perc <- c(0, diff(main_data$temperature)/main_data$temperature[-length(main_data$temperature)])
brks <- economics$date[seq(1, length(main_data$time), 1)]
lbls <- lubridate::year(main_data$time[seq(1, length(main_data$time), 1)])
main_data |> 
  ggplot(aes(tie, perc)) + 
  geom_area() + 
  scale_x_date(breaks = brks, labels = lbls) + 
  theme(axis.text.x = element_text(angle = 90)) + 
  labs(title = "Area Chart", 
       subtitle = "Perc Returns for Personal Savings", 
       y = "% Returns for Personal savings", 
       caption = "Source: economics")
```
